### ISSUE TITLE
URL to the Jenkins instance- Error: Jenkins response: requested resource is not available

### ISSUE THREAD

**Issue by SabareeshSS** [Nerdwin15/stash-jenkins-postreceive-webhook#107]
Hi!
What is the URL i should provide to the Jenkins Instance.

![image](https://cloud.githubusercontent.com/assets/7418432/6329099/74c925da-bb93-11e4-9bf9-4a876f33ce52.png)

**Comment by mikesir87** [comment]
Do you have the Git plugin installed in your Jenkins instance?  It looks like the endpoint that it's trying to hit isn't registered.

**Comment by mikesir87** [comment]
Closing as no response provided.  Feel free to comment back if you are still having issues.

**Comment by seetharamank** [comment]
please help me
I am also getting same error . jenkins integrate with bit bucket
