### ISSUE TITLE
Why I push only one branch , but all branches are build?

### ISSUE THREAD

**Issue by songcy6202** [Nerdwin15/stash-jenkins-postreceive-webhook#138]
I had read other issues but i can't figure out why still,can u give me help?
As I'm not using jeckins , I write a trigger myself and I get http request from the hook and get args from request to do somework .I push one branch to git repository,but I got all branches hook info to my trigger. Is that working correctly?

**Comment by mikesir87** [comment]
What are you seeing?  What do you mean you "got all branches hook info"?  Can you post a sample URL that it's triggering?

**Comment by songcy6202** [comment]
Sorry for cofusing you, my english is not good.The hook worked well. After checking the old codes carefully, I found  when my trigger got git repo and commid_hash from hook it worked on all branches. I have fixed it.And Thanks a lot !
