### ISSUE TITLE
TriggerBuild button no longer passes the "branch" specifier

### ISSUE THREAD

**Issue by daviwilliams** [Nerdwin15/stash-jenkins-postreceive-webhook#143]
Since updating from 2.6 to 2.7, the Pull Request TriggerBuild button no longer specifies the branch name when sending notification to Jenkins.  This is causing all jobs to build the specified commit.  

Example using 2.6:
/git/notifyCommit?url=ssh%3A%2F%2Fgit%40stashtest%3A7999%2Fchris%2Fbranchtest.git&branches=feature&sha1=4c8fffc81cf4566bde0230874e0e2beedb3fe89d

Example using 2.7:
GET /git/notifyCommit?url=ssh%3A%2F%2Fgit%40stash%3A7999%2Fchris%2Fbranchtest.git&sha1=f17fb0f4ed9d55a3543237e873babeb57863dcfa

**Comment by mikesir87** [comment]
Yes. This has been resolved with PR #136 and an update will be coming in the next day or two.
