### ISSUE TITLE
Is it possible to get a release with the branch parameter fix for the jenkins notification URL

### ISSUE THREAD

**Issue by nortonsj** [Nerdwin15/stash-jenkins-postreceive-webhook#146]
Would it be possible to get a release that includes the branch parameter fix for the Jenkins notification URL (commit b3c8baa2c9218851a44307d7a4046599808fd2f6)?

Our build system relies on filtering by the branch name provided in the notification from stash. Currently on 2.7.0 the branch name is not being passed correctly, causing all build jobs for a particular project to be triggered at the same time. 

Unfortunately downgrading to an older version is not an option as other groups use our stash server and rely on the newer version.

**Comment by mikesir87** [comment]
Yes. I am working on it right now.  I was hoping to get another bug fix included with this release, but was unable to get it tracked down.  You should see the update shortly.
