### ISSUE TITLE
Support Bitbucket 4.6.1

### ISSUE THREAD

**Issue by esper** [Nerdwin15/stash-jenkins-postreceive-webhook#170]
Please add support for the new Bitbucket Server version 4.6.1 (17 May 2016).

**Comment by mikesir87** [comment]
When Atlassian releases new updates for Bitbucket, the plugin's compatibility is normally auto-updated to the latest version. For some reason, it didn't do that this time and stopped at 4.6.0.  I've updated the metadata to support 4.6.1.  Let me know if that doesn't seem to be the case on your end.

**Comment by esper** [comment]
Thank you for the quick fix!
