### ISSUE TITLE
Support Bitbucket 5.0

### ISSUE THREAD

**Issue by ViceIce** [Nerdwin15/stash-jenkins-postreceive-webhook#190]
Bitbucket 5.0 is out, please add support.

Regards

**Comment by kevindeuel** [comment]
Has there been any response to this request? 
I tried to contact the developer using the vendor contact from the Atlassian site, but the email is returned with "user unknown" error.

**Comment by george-007** [comment]
From README:
> Looking for maintainer! As it's probably pretty obvious now, I haven't been able to maintain this plugin. It started as a one-man job and I eventually migrated away from Stash/Bitbucket to something a little more maintainable for a one-man shop. If you're interested in supporting this plugin, please contact me at mikesir87[at]gmail[dot]com.

**Comment by mikesir87** [comment]
Hello all! I'm sorry for the quietness here. As @george-007 mentioned, yes... I'm looking for a maintainer as I'm not able to maintain this project anymore.  However... since it's apparently completely not working in 5.0 right now and so many people are depending on it, I will see if I can get it at least get it up and running.

@krussan - I see your commit there.  Have you been able to confirm that that commit does indeed get the plugin working on 5.0?  Can any others confirm as well?  If it looks good, I'll go ahead and merge and then get a release targeting 5.0.

If anyone is interested in maintaining the plugin long-term, please let me know!

**Comment by krussan** [comment]
@mikesir87 Yes. It works in our setup with BitBucket 5.0.1.

**Comment by TimTim74** [comment]
Installed it today on 5.0.1 and cannot get it to work. Not even an error message??

**Comment by TimTim74** [comment]
@krussan : What version of jenkins are you running then? We have 2.46.2 currently.

**Comment by TimTim74** [comment]
@mikesir87 : Yes it works for us as well. Running Bitbucket 5.0.1 and Jenkins 2.46.2. Works like a charm now. 

I must have done something wrong before, because now I reinstalled the plugin and it works like a charm.

**Comment by clarenceh** [comment]
@mikesir87 
Hi this is Clarence, who is using Jenkins and upgraded to Bitbucket 5.1.0 recently. I also managed to make the plugin work in my installation by doing the following:
- Clone your repository
- Make the changes as mentioned in PR #191 (the pom file version properties and 1 Java file) 
- Build the plugin locally
- In my Bitbucket 5 server, uninstall 3.0.1, and then manually upload the newly built plugin

I really appreciate your work so far in providing this useful plugin for the community and understand that you are not able to maintain this plugin anymore. However, I believe that by just merge the PR #191 and then release a minor update 3.0.2, it will work on Bitbucket 5 and help out a lot of folks who had upgraded and using the plugin.

Best regards.
Clarence

**Comment by stesieber** [comment]
@mikesir87 : the PR #191 of @alexBraidwood worked as expected for us - we installed the plugin in Bitbucket 5.1.(packaged with maven).

**Comment by pySilver** [comment]
@clarenceh how do I build a plugin from source?

**Comment by keeneym** [comment]
@mikesir87  I have also built and deployed PR #191 and can confirm it is working for me with BitBucket 5.2.2 and Jenkins 2.70

**Comment by ppodgorsek** [comment]
@mikesir87, the fix from @alexBraidwood in PR #191 looks good. Could it be merged in order to have a working plugin on the Atlassian marketplace please?

**Comment by mikesir87** [comment]
Hello all! Sorry for the radio silence... I'm working to add a few co-maintainers that can help keep up with the code, testing, and merge pull requests.  I'll be adding @alexBraidwood as a maintainer and others as the requests come in. PR #191 will be merged and I'll push to the Marketplace! 🎉

**Comment by mikesir87** [comment]
AND... released!  Please pull the update and verify if it's working out for you guys!

**Comment by ppodgorsek** [comment]
PR #199 has been created to correctly set the dependencies in the POM file for the latest Bitbucket version.

**Comment by ViceIce** [comment]
This is working now. Should i close the issue?
