### ISSUE TITLE
Does this work for pull requests?

### ISSUE THREAD

**Issue by abraithwaite** [Nerdwin15/stash-jenkins-postreceive-webhook#23]
I saw the blog post about requiring build passes in order to merge a pull request, but I couldn't find any pull request hook plugins.

Does this run every time a new pull request is made?

If so, does it run again after the pull request is merged?

**Comment by nightwolfzor** [comment]
As an alternative which still works with this plugin is a Stash pull request builder plugin which lets you do pre merge builds. Much like the GitHub pull request builder; https://github.com/nemccarthy/stash-pullrequest-builder-plugin
