### ISSUE TITLE
Trigger build on new push to pull requests

### ISSUE THREAD

**Issue by mikesir87** [Nerdwin15/stash-jenkins-postreceive-webhook#38]
(copying comments from blog)

-- Comment from 12/4 11:10

We tried to use your plugin with Stash Pull Requests, but encountered a problem, I know that it is on Stash side, but want to ask if you have some workaround in mind:

What we want to accomplish is:
1. Open Pull Request in Stash for specific
2. After Pull Request is openned trigger "Pull Request Build Job" in Jenkins
   (we are using Git Plugin in Jenkins and specifying refspec
   parameters: "+refs/pull-requests/_:refs/remotes/origin/pull-requests/_"
   and building the "origin/pull-requests/*/from" branch) 
   Jenkins WebHook plugin is setup to trigger job by commit to Stash Repo
3. Initiate Review process with changes discussion
4. Do commit changes and update pull-request with new commits due to discussion 
   (Here we get trouble, cause your plugin is sending trigger after commit, but poll scm from Jenkins can't find nothing, cause stash updates the reference - "refs/pull-requests/*/from" only if it was Approved in Pull Request)
5. We want to Trigger Jenkins build for new commits in the "Pull Request Build Job"
6. Review again, approve, merge

But to update reference and have additional commits in the same Pull we need to Approve and Unapprove each time after commit, which is makes no sense

Do you have any workaround or any ideas how to adopt this to Pull Requests process?

------ Comment on 12/4 11:57

I got a fast reply from Atlassian Developer according to this. 
Michael could be interesting for you as a feature, since he also submitted some code snippet how to solve this - https://answers.atlassian.com/questions/239988/change-pull-request-refs-after-commit-instead-of-after-approval-or-workaround

**Comment by prosenjit87** [comment]
Ok so in **GitLab** if you would like to trigger auto build using **Poll SCM** for only **merge requests** you can use the below syntax under **Refspec** and **Branch Specifier (blank for 'any')** respectively .... it will work perfectly

`+refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*`
`**`

![image](https://user-images.githubusercontent.com/23166358/90670950-9a87e300-e271-11ea-93d2-ce7cce367ece.png)
