### ISSUE TITLE
Manual trigger button

### ISSUE THREAD

**Issue by melvyndekort** [Nerdwin15/stash-jenkins-postreceive-webhook#45]
There are circumstances where it's very handy to have a manual Jenkins trigger button available.

I'll explain a situation that we've come across.
When you create a pull-request from branch X to branch Y, the latest version of the plugin triggers a build on Jenkins, all is well.
However, when another developer would then commit something to branch Y, the build of the pull-request is out of date, since the target branch was modified.
When you would then open the pull-request in the Stash pages, a new automerge is created in the background.
At this moment no build is triggered since every open pull-request with target branch Y would have to be triggered.
This would stress the Jenkins buildserver too much.

In our Stash setup we use the stash-jenkins-postreceive-webhook plugin combined with the stash-build-status-plugin.
The latter one disables the Stash merge-button until a successful build of the automerge was performed.
This will however also block the pull-request from being merged when branch Y was updated in the meanwhile.

A button to trigger a build manually would circumvent this problem.

**Comment by patelnidhice** [comment]
I dont see any button to trigger the build when pull request is created. I have latest version of webhook plugin installed, am I missing anything?
