### ISSUE TITLE
Configure webhook to trigger only if push to a specific branch

### ISSUE THREAD

**Issue by anuragkapur** [Nerdwin15/stash-jenkins-postreceive-webhook#58]
Is it possible to configure the webhook to be triggered if there is a change to a specific branch?

For example, I would like to trigger a jenkins job only if there is a push to a branch called "release".

**Comment by mozinrat** [comment]
Hi @mikesir87 is it available for bitbucket as well.

**Comment by metadan** [comment]
Yep I would like this on bitbucket also.

**Comment by Korijn** [comment]
One more request vote for Bitbucket :+1:

**Comment by aqyblitz** [comment]
Hi, I'm using this plug-in right now and would like to specify that Stash/BitBucket Server only sends a commit notification to Jenkins on a certain branch, aka the whitelist feature. My branch name is prefixed with "release/" and I noticed that this does not work. I created a mirrored branch and named it "test", which worked out, but I'm wondering if the "/" is breaking the whitelist feature? Please advise; thanks.

**Comment by rsarunprashad** [comment]
Hi @mikesir87 

I am facing an issue integrating Stash(3.2) with Jenkins.
My Observation is Local git commit (local)are firing GET request to jenkins,but git push(push) is not firing .
As a result ,Jenkins polling is not detecting any Changes and jenkins statys 1 commit behind.

**Comment by Nagendra080389** [comment]
Does this only work with BitBucket or will it also work with Github. Because I think github plugin for jenkins does not have branch filter in webhook.
Can I implement same thing in Github-plugin for jenkins too,

**Comment by amanoj553** [comment]
I want to configure webhooks in GitHub for particular branch commit changes then Jenkins job needs to build.

**Comment by amanoj553** [comment]
Please give me solution for above query
