### ISSUE TITLE
Webhook trigering multiple builds

### ISSUE THREAD

**Issue by phardakerffdc** [Nerdwin15/stash-jenkins-postreceive-webhook#59]
Hi,

we're making heavy use of your webhook and firstly I'd like to say how fantastic it is!

We have one slight issue - we have multiple jenkins jobs pointing at the same Stash repo, each job configured to build a different branch.

What I'm seeing is, when I push to one branch, the build for that branch is triggered, but also builds for other branches too.

Could this be a problem in the way I've set things up? Am I misunderstanding something? Or could it be a bug in the webhook?

Many thanks

**Comment by ixre** [comment]
@phardakerffdc 
hi, i have same needes.

**Comment by ixre** [comment]
@phardakerffdc

Hi, I have the same needs. you can pass `Build when a change is pushed to GitLab` -> Allowed branches settings  caught one trigger. hope it's  helpfully for you.
