### ISSUE TITLE
For a single job, multiple builds are sometimes triggered for a single commit

### ISSUE THREAD

**Issue by dhumeniuk** [Nerdwin15/stash-jenkins-postreceive-webhook#63]
On an intermittent basis, a single job will be started twice for a single change. When I push a commit to Stash, sometimes the same Jenkins job (for that development branch or maybe a job that runs off the master when merging to the master) will be started twice.

I do have "Execute concurrent builds if necessary" enabled for the job in Jenkins as I do want to have multiple builds running if there is a newer commit pushed while the existing build is still running.

**Comment by iginzburg** [comment]
I am having the same issue. Any updates?

**Comment by chasepeeler** [comment]
We worked around the issue by setting a quiet time - so, I'm not sure if it's still happening or not. I can't remove the quiet time and confirm right now.

**Comment by pavlop-asg** [comment]
The same for me

**Comment by chr0n1x** [comment]
bump

**Comment by patelnidhice** [comment]
I see build getting triggered for 1. branch creation 2. git push 3. pull request creation 4. merge to master, is there anyway we can skip triggering build while branch creation?

**Comment by pkahn-attivio** [comment]
Hi Folks, 
We see this two and we noticed a pattern jenkins reports humans triggering push for first build and our build user triggering the second.   We worked around the problem by placing a user filter on the trigger on our build user.  The build user doesn't commit, it just makes tags.

Our theory (mythology really) is that because we tag as a part of our builds each build triggers another build due to the tag.   We cant really rep it.

**Comment by victorv** [comment]
Same problem here. In our case we get two notifications in github that point to the same build but the status of one is "building" and the other is "complete"
![untitled](https://cloud.githubusercontent.com/assets/59046/20116282/e816778e-a5b8-11e6-80e9-ccc0e8c2dee8.jpg)

**Comment by anthuwan13** [comment]
Was there any solution found for this issue , as we face the same issue now.

**Comment by epodoliak-tfin** [comment]
I join. I have the same problem with merge develop in master

**Comment by saurabh-pathak94** [comment]
We are seeing builds being triggered twice for same commit notification if Branch Specifier is set to '**' (any). I am believe it is related to this issue.

**Comment by Redempter** [comment]
Hey, I am having the same issue with my Jenkins server, one commit, two builds being triggered for the same job. Has anyone found something for this?

**Comment by rzinnatullin** [comment]
Hi, I'm experiencing the same issue with Jenkins. However, this doesn't happen with TeamCity server. I think TeamCity can somehow filter duplicate triggerings.

**Comment by qizer** [comment]
Hi,
Looks like this plugin not free now and this version out of support \=

I also have the same issue.

For me there two triggers:
1. Branch event 
2. commit notification

**Comment by Cognimity** [comment]
Is there any solution to this. I am facing the same problem....
