### ISSUE TITLE
Keep repeated builds in Stash does not completely work 

### ISSUE THREAD

**Issue by pietervogelaar** [Nerdwin15/stash-jenkins-postreceive-webhook#97]
The option "Keep repeated builds in Stash" does not completely work in 2.5.0 / 2.6.0.

If you click in Stash on the build status icon all build are displayed correctly with a success or fail icon. So that part works nice. But the icon outside the popup after the commit description is not updated.

My test:
build succes => success icon
build failure => failure icon
build failure => failure icon
build success => failure icon

So It switched one time from success to failure but never goes back to success. The busy icon is not set also.

**Comment by mikesir87** [comment]
The option to keep repeated builds in Stash is actually a Stash configuration and not something I can tweak from my plugin.  So, its behavior and how it presents the icons is beyond what I'm able to interact with.

Also, the busy icons are not part of my plugin either.  The Jenkins server can send a notification to Stash to let it know of a current build.  But, that's configuration in Jenkins, not in my Stash plugin.  If your Jenkins instance is sending the notification and Stash still isn't displaying it, I'd ping the Stash development team, as those icons are part of Stash core.

So... sorry for the lack of help here.  Let me know if there's anything else I can help out with.

**Comment by pietervogelaar** [comment]
Okay, no problem.. thanks for your reply! I will notify the Stash dev team.
