### ISSUE TITLE
Add configuration option to hide the 'trigger build' button

### ISSUE THREAD

**Issue by Wilfred** [Nerdwin15/stash-jenkins-postreceive-webhook#98]
As mentioned in #81, the 'trigger build' button can be confusing. It simply informs Jenkins that new commits are available. It doesn't force a build right now: the build queue could be full, or Jenkins may not even have a job for that git URL.

However, the ability to notify Jenkins as soon as a pull request is merged, is really useful. Without it, we have to configure Jenkins to just poll git continually. Could we provide an option to disable or hide the button?

**Comment by tldavies** [comment]
What update/version will Fix #98 be in?
